addresses:
  api: "localhost:8080"
  account: "localhost:8101"
  products: "localhost:8102"
  transfers: "localhost:8103"
database:
  dsn: "port=5445 host=localhost user=user dbname=merch password=123456 sslmode=disable"