addresses:
  api: "api:8080"
  account: "account:8101"
  products: "products:8102"
  transfers: "transfers:8103"
database:
  dsn: "port=5432 host=pg user=user dbname=test password=123456 sslmode=disable"
public:
  host : "localhost"
  port :  8080
  database:
    host: "localhost"
    port: 5445