// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: transfers.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Transfers_SendCoins_FullMethodName = "/Transfers/SendCoins"
)

// TransfersClient is the client API for Transfers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransfersClient interface {
	SendCoins(ctx context.Context, in *SendCoinsReq, opts ...grpc.CallOption) (*SendCoinsRes, error)
}

type transfersClient struct {
	cc grpc.ClientConnInterface
}

func NewTransfersClient(cc grpc.ClientConnInterface) TransfersClient {
	return &transfersClient{cc}
}

func (c *transfersClient) SendCoins(ctx context.Context, in *SendCoinsReq, opts ...grpc.CallOption) (*SendCoinsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCoinsRes)
	err := c.cc.Invoke(ctx, Transfers_SendCoins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransfersServer is the server API for Transfers service.
// All implementations must embed UnimplementedTransfersServer
// for forward compatibility.
type TransfersServer interface {
	SendCoins(context.Context, *SendCoinsReq) (*SendCoinsRes, error)
	mustEmbedUnimplementedTransfersServer()
}

// UnimplementedTransfersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransfersServer struct{}

func (UnimplementedTransfersServer) SendCoins(context.Context, *SendCoinsReq) (*SendCoinsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCoins not implemented")
}
func (UnimplementedTransfersServer) mustEmbedUnimplementedTransfersServer() {}
func (UnimplementedTransfersServer) testEmbeddedByValue()                   {}

// UnsafeTransfersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransfersServer will
// result in compilation errors.
type UnsafeTransfersServer interface {
	mustEmbedUnimplementedTransfersServer()
}

func RegisterTransfersServer(s grpc.ServiceRegistrar, srv TransfersServer) {
	// If the following call pancis, it indicates UnimplementedTransfersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Transfers_ServiceDesc, srv)
}

func _Transfers_SendCoins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCoinsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransfersServer).SendCoins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transfers_SendCoins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransfersServer).SendCoins(ctx, req.(*SendCoinsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Transfers_ServiceDesc is the grpc.ServiceDesc for Transfers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transfers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Transfers",
	HandlerType: (*TransfersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCoins",
			Handler:    _Transfers_SendCoins_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transfers.proto",
}
