// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.28.3
// source: transfers.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendCoinsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUser      string                 `protobuf:"bytes,1,opt,name=FromUser,proto3" json:"FromUser,omitempty"`
	ToUser        string                 `protobuf:"bytes,2,opt,name=ToUser,proto3" json:"ToUser,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCoinsReq) Reset() {
	*x = SendCoinsReq{}
	mi := &file_transfers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCoinsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCoinsReq) ProtoMessage() {}

func (x *SendCoinsReq) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCoinsReq.ProtoReflect.Descriptor instead.
func (*SendCoinsReq) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{0}
}

func (x *SendCoinsReq) GetFromUser() string {
	if x != nil {
		return x.FromUser
	}
	return ""
}

func (x *SendCoinsReq) GetToUser() string {
	if x != nil {
		return x.ToUser
	}
	return ""
}

func (x *SendCoinsReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SendCoinsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCoinsRes) Reset() {
	*x = SendCoinsRes{}
	mi := &file_transfers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCoinsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCoinsRes) ProtoMessage() {}

func (x *SendCoinsRes) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCoinsRes.ProtoReflect.Descriptor instead.
func (*SendCoinsRes) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{1}
}

type Received struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUser      string                 `protobuf:"bytes,1,opt,name=FromUser,proto3" json:"FromUser,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Received) Reset() {
	*x = Received{}
	mi := &file_transfers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Received) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Received) ProtoMessage() {}

func (x *Received) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Received.ProtoReflect.Descriptor instead.
func (*Received) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{2}
}

func (x *Received) GetFromUser() string {
	if x != nil {
		return x.FromUser
	}
	return ""
}

func (x *Received) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Sent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUser        string                 `protobuf:"bytes,1,opt,name=ToUser,proto3" json:"ToUser,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sent) Reset() {
	*x = Sent{}
	mi := &file_transfers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sent) ProtoMessage() {}

func (x *Sent) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sent.ProtoReflect.Descriptor instead.
func (*Sent) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{3}
}

func (x *Sent) GetToUser() string {
	if x != nil {
		return x.ToUser
	}
	return ""
}

func (x *Sent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CoinsHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      []*Received            `protobuf:"bytes,1,rep,name=Received,proto3" json:"Received,omitempty"`
	Sent          []*Sent                `protobuf:"bytes,2,rep,name=Sent,proto3" json:"Sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinsHistory) Reset() {
	*x = CoinsHistory{}
	mi := &file_transfers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinsHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinsHistory) ProtoMessage() {}

func (x *CoinsHistory) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinsHistory.ProtoReflect.Descriptor instead.
func (*CoinsHistory) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{4}
}

func (x *CoinsHistory) GetReceived() []*Received {
	if x != nil {
		return x.Received
	}
	return nil
}

func (x *CoinsHistory) GetSent() []*Sent {
	if x != nil {
		return x.Sent
	}
	return nil
}

type GetHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryReq) Reset() {
	*x = GetHistoryReq{}
	mi := &file_transfers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryReq) ProtoMessage() {}

func (x *GetHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryReq.ProtoReflect.Descriptor instead.
func (*GetHistoryReq) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{5}
}

func (x *GetHistoryReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetHistoryRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinsHistory  *CoinsHistory          `protobuf:"bytes,1,opt,name=coinsHistory,proto3" json:"coinsHistory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRes) Reset() {
	*x = GetHistoryRes{}
	mi := &file_transfers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRes) ProtoMessage() {}

func (x *GetHistoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRes.ProtoReflect.Descriptor instead.
func (*GetHistoryRes) Descriptor() ([]byte, []int) {
	return file_transfers_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistoryRes) GetCoinsHistory() *CoinsHistory {
	if x != nil {
		return x.CoinsHistory
	}
	return nil
}

var File_transfers_proto protoreflect.FileDescriptor

var file_transfers_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5a, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54,
	0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x0e, 0x0a,
	0x0c, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x22, 0x3e, 0x0a,
	0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x72, 0x6f,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x72, 0x6f,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x36, 0x0a,
	0x04, 0x53, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x50, 0x0a, 0x0c, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x25, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x64, 0x52, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x04,
	0x53, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x53, 0x65, 0x6e,
	0x74, 0x52, 0x04, 0x53, 0x65, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x0c, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6f,
	0x69, 0x6e, 0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0c, 0x63, 0x6f, 0x69, 0x6e,
	0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x32, 0x64, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x73, 0x12, 0x29, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x69,
	0x6e, 0x73, 0x12, 0x0d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x0d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x12, 0x2c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x0e,
	0x2e, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0e,
	0x2e, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x42, 0x14,
	0x5a, 0x12, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_transfers_proto_rawDescOnce sync.Once
	file_transfers_proto_rawDescData []byte
)

func file_transfers_proto_rawDescGZIP() []byte {
	file_transfers_proto_rawDescOnce.Do(func() {
		file_transfers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfers_proto_rawDesc), len(file_transfers_proto_rawDesc)))
	})
	return file_transfers_proto_rawDescData
}

var file_transfers_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_transfers_proto_goTypes = []any{
	(*SendCoinsReq)(nil),  // 0: SendCoinsReq
	(*SendCoinsRes)(nil),  // 1: SendCoinsRes
	(*Received)(nil),      // 2: Received
	(*Sent)(nil),          // 3: Sent
	(*CoinsHistory)(nil),  // 4: CoinsHistory
	(*GetHistoryReq)(nil), // 5: GetHistoryReq
	(*GetHistoryRes)(nil), // 6: GetHistoryRes
}
var file_transfers_proto_depIdxs = []int32{
	2, // 0: CoinsHistory.Received:type_name -> Received
	3, // 1: CoinsHistory.Sent:type_name -> Sent
	4, // 2: GetHistoryRes.coinsHistory:type_name -> CoinsHistory
	0, // 3: Transfers.SendCoins:input_type -> SendCoinsReq
	5, // 4: Transfers.GetHistory:input_type -> GetHistoryReq
	1, // 5: Transfers.SendCoins:output_type -> SendCoinsRes
	6, // 6: Transfers.GetHistory:output_type -> GetHistoryRes
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_transfers_proto_init() }
func file_transfers_proto_init() {
	if File_transfers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfers_proto_rawDesc), len(file_transfers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfers_proto_goTypes,
		DependencyIndexes: file_transfers_proto_depIdxs,
		MessageInfos:      file_transfers_proto_msgTypes,
	}.Build()
	File_transfers_proto = out.File
	file_transfers_proto_goTypes = nil
	file_transfers_proto_depIdxs = nil
}
